# This is a basic workflow to help you get started with Actions

name: Azure Deployment

on:

  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  # This workflow contains a single job called "Deploy"

  deploy:
    runs-on: ubuntu-latest
    steps:

    - name: Login to Azure via Az module
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
        enable-AzPSSession: true

    - name: Checkout Source Code
      uses: actions/checkout@v2

    # - name: Deploy using Azure Powershell script
    #   uses: azure/powershell@v1
    #   with:
    #     inlineScript: |
    #       --template-file ./KeyVaultBackup.ps1
    
    - name: Deploy PowerShell script
      shell: pwsh
      run: |
        .\KeyVaultBackup.ps1

 



